# Generated by Django 3.2.13 on 2023-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_tac',
            field=models.BooleanField(default=False),
        ),
    ]
