# Generated by Django 3.2.13 on 2022-11-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawDatamartAccountingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_accounting_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartAddonDetailHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_addon_detail_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartAddonHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'Raw_Datamart_Addon_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartAddonHistoryPostgres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_addon_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartBusiestItemTimeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_busiest_item_time_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartBusiestSellingTimeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_busiest_selling_time_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartCashierHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_cashier_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartMerchantOutletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_merchant_outlet_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartPromoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_promo_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartSubmissionEcommerceGrabfoodHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_submission_ecommerce_grabfood_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartSubmissionWalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_submission_wallet_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartSupportTrxHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_support_trx_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartTransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'Raw_Datamart_Transaction_History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartTransactionHistoryPostgres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_transaction_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartTransactionPaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_transaction_payment_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartTransactionTypeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_transaction_type_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryDatamartAkunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_current', models.DateTimeField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('num_row', models.TextField()),
                ('time_process', models.FloatField()),
                ('ts_end', models.DateTimeField()),
                ('act_date', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recovery_history_datamart_akunting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryDatamartBusiestSellingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_current', models.DateTimeField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('num_row', models.TextField()),
                ('time_process', models.FloatField()),
                ('ts_end', models.DateTimeField()),
                ('act_date', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recovery_history_datamart_busiest_selling_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryDatamartProduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_current', models.DateTimeField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('num_row', models.TextField()),
                ('time_process', models.FloatField()),
                ('ts_end', models.DateTimeField()),
                ('act_date', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recovery_history_datamart_produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryDatamartSubVarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_current', models.DateTimeField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('num_row', models.TextField()),
                ('time_process', models.FloatField()),
                ('ts_end', models.DateTimeField()),
                ('act_date', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recovery_history_datamart_sub_varian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryDatamartVarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_current', models.DateTimeField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('num_row', models.TextField()),
                ('time_process', models.FloatField()),
                ('ts_end', models.DateTimeField()),
                ('act_date', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'recovery_history_datamart_varian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistoryAkunting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recovery', models.SmallIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('data_target', models.IntegerField()),
                ('data_source', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_akunting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistoryBusiestSellingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recovery', models.SmallIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('data_target', models.IntegerField()),
                ('data_source', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_busiest_selling_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistoryProduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recovery', models.SmallIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('data_target', models.IntegerField()),
                ('data_source', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistorySubVarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recovery', models.SmallIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('data_target', models.IntegerField()),
                ('data_source', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_sub_varian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistoryVarian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recovery', models.SmallIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('data_target', models.IntegerField()),
                ('data_source', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_varian',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistoryWaktuTeramai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_recovery', models.SmallIntegerField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('data_target', models.IntegerField()),
                ('data_source', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_waktu_teramai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityAndRecoveryScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nifi_group_name', models.CharField(max_length=100)),
                ('start_at', models.CharField(max_length=20)),
                ('end_at', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
