# Generated by Django 3.2.13 on 2022-11-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validityandrecoveryscheduler',
            old_name='nifi_group_name',
            new_name='etl_name',
        ),
        migrations.AddField(
            model_name='validityandrecoveryscheduler',
            name='recovery_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
