# Generated by Django 3.2.13 on 2022-11-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_validityandrecoveryscheduler_cron_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validityandrecoveryscheduler',
            name='cron_state',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='validityandrecoveryscheduler',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='validityandrecoveryscheduler',
            table='home_validity_recovery_scheduler',
        ),
    ]
