# Generated by Django 3.2.13 on 2023-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_airflowfailedtask_airflowgeneralerror_alert_alertdetail_alerthistory_rawdatamartproducthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDatamartOutletSellingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_outlet_selling_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartProductSalesRefundHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_product_sales_refund_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartTrasactionWalletDynamicHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_transaction_wallet_dynamic_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ValidityHistoryCDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField()),
                ('data_source', models.BigIntegerField()),
                ('data_target', models.BigIntegerField()),
                ('execution_time', models.FloatField()),
                ('actdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'validity_history_cdc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('etl_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'home_validity_recovery_mapping',
            },
        ),
        migrations.DeleteModel(
            name='RawDatamartAddonHistoryPostgres',
        ),
        migrations.DeleteModel(
            name='RawDatamartTransactionHistoryPostgres',
        ),
        migrations.AlterModelTable(
            name='rawdatamartaddonhistory',
            table='raw_datamart_addon_history',
        ),
        migrations.AlterModelTable(
            name='rawdatamarttransactionhistory',
            table='raw_datamart_transaction_history',
        ),
    ]
