# Generated by Django 3.2.13 on 2023-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230410_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDatamartBatchSerialNumberHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_batchserial_number_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartComplimentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_compliment_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartDailyReportHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_daily_report_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartJournalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_journal_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartOrderTypeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_order_type_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartOutletSalesHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_outlet_sales_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartReservationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_reservation_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartSubextrasHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_subextra_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartUtilizationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_utilization_history',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='alertdetail',
            name='detail',
            field=models.JSONField(default=None),
        ),
    ]
