# Generated by Django 3.2.13 on 2023-07-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230712_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdetail',
            name='detail',
            field=models.JSONField(default=None, null=True),
        ),
    ]
