# Generated by Django 3.2.13 on 2023-07-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_alertdetail_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDatamartJurnalHutangHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_jurnal_hutang_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartJurnalPiutangHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_jurnal_piutang_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryHardDelete',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ts_current', models.DateTimeField()),
                ('id_user', models.BigIntegerField()),
                ('id_cabang', models.BigIntegerField()),
                ('time_process', models.FloatField()),
                ('actdate', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'recovery_history_hard_delete',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionsHistory',
            fields=[
                ('id_transaction', models.BigIntegerField(primary_key=True, serialize=False)),
                ('m_user_id_user', models.BigIntegerField()),
                ('m_cabang_id_cabang', models.BigIntegerField()),
                ('transaction_tgl', models.DateTimeField()),
                ('updatedate', models.DateTimeField()),
                ('createdate_datalake', models.DateTimeField()),
            ],
            options={
                'db_table': 'transactions_history',
                'managed': False,
            },
        ),
    ]
