# Generated by Django 3.2.13 on 2023-09-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rawdatamartjurnalhutanghistory_rawdatamartjurnalpiutanghistory_recoveryhistoryharddelete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_m_cms_menu', models.IntegerField()),
                ('report_name', models.TextField()),
                ('history_table_name', models.TextField()),
                ('datamart_url', models.TextField()),
                ('non_datamart_url', models.TextField()),
                ('is_automate', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'dashboard_report_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MCMSMenuRetina',
            fields=[
                ('id_m_cms_menu', models.IntegerField(primary_key=True, serialize=False)),
                ('m_cms_menu_name', models.TextField()),
                ('m_cms_menu_english_name', models.TextField()),
                ('m_cms_menu_id_parent', models.IntegerField()),
                ('m_cms_menu_controller', models.TextField()),
                ('m_cms_menu_function', models.TextField()),
                ('m_cms_menu_url', models.TextField()),
                ('m_cms_menu_is_menu', models.IntegerField()),
                ('m_cms_menu_is_menu_android', models.IntegerField()),
                ('m_cms_menu_is_golang', models.IntegerField()),
                ('m_cms_menu_icon_src', models.TextField()),
                ('m_cms_menu_premium', models.IntegerField()),
                ('m_cms_menu_seq', models.IntegerField()),
                ('is_android_transactional', models.IntegerField()),
                ('is_have_view', models.IntegerField()),
                ('is_have_create', models.IntegerField()),
                ('is_have_update', models.IntegerField()),
                ('is_have_void', models.IntegerField()),
                ('is_have_delete', models.IntegerField()),
                ('is_menu_mobile', models.IntegerField()),
                ('Page_Banner_id_page_banner', models.IntegerField()),
                ('createdby', models.IntegerField()),
                ('createdate', models.DateTimeField()),
                ('updateby', models.IntegerField()),
                ('updatedate', models.DateTimeField()),
                ('active_status', models.IntegerField()),
                ('menu_type', models.IntegerField()),
                ('menu_alias', models.TextField()),
            ],
            options={
                'db_table': 'M_CMS_Menu_Retina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartAkuntingRecoveryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_live_recovery_accounting_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartMerchantTransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_merchant_transaction_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawDatamartPaymentTypeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actdate', models.DateTimeField()),
                ('ts_current', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('num_row', models.IntegerField()),
                ('time_process', models.FloatField()),
                ('params', models.TextField()),
            ],
            options={
                'db_table': 'raw_datamart_payment_type_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryHistoryPromo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('m_user_id_user', models.BigIntegerField()),
                ('m_cabang_id_cabang', models.BigIntegerField()),
                ('transaction_tgl', models.DateField()),
                ('createdate_datalake', models.DateTimeField()),
                ('is_recovered_product', models.BooleanField()),
                ('is_recovered_promo', models.BooleanField()),
                ('is_recovered_compliment', models.BooleanField()),
            ],
            options={
                'db_table': 'transaction_promo_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SettingMapping',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setting_name', models.CharField(max_length=100)),
                ('value', models.JSONField(default=None, null=True)),
            ],
            options={
                'db_table': 'home_setting_mapping',
            },
        ),
        migrations.DeleteModel(
            name='RawDatamartAddonDetailHistory',
        ),
        migrations.DeleteModel(
            name='RawDatamartAddonHistory',
        ),
        migrations.DeleteModel(
            name='RawDatamartOutletSellingHistory',
        ),
        migrations.DeleteModel(
            name='RawDatamartProductHistory',
        ),
        migrations.DeleteModel(
            name='RawDatamartReservationHistory',
        ),
        migrations.AlterModelTable(
            name='rawdatamarttransactionpaymenthistory',
            table='raw_transaction_type_payment_history',
        ),
        migrations.AlterModelTable(
            name='rawdatamarttransactiontypehistory',
            table='raw_transaction_type_payment_history',
        ),
    ]
